// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGjeBaWJ3NsVlaM0SLDjWxuXhueimbgI',
    appId: '1:919617836894:web:530331318a36b90a83a1cf',
    messagingSenderId: '919617836894',
    projectId: 'medigo-app-73a5d',
    authDomain: 'medigo-app-73a5d.firebaseapp.com',
    storageBucket: 'medigo-app-73a5d.firebasestorage.app',
    measurementId: 'G-MXTEM2B5XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbw9eUCgoUZkzFpjkos61abeHMtPLE60',
    appId: '1:919617836894:android:2ec5de0f3b20b4e883a1cf',
    messagingSenderId: '919617836894',
    projectId: 'medigo-app-73a5d',
    storageBucket: 'medigo-app-73a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFu4XzjJ35gXaaVsGtUPiIuZdxBNd_QI',
    appId: '1:919617836894:ios:67030648c4ccdc0a83a1cf',
    messagingSenderId: '919617836894',
    projectId: 'medigo-app-73a5d',
    storageBucket: 'medigo-app-73a5d.firebasestorage.app',
    iosBundleId: 'com.example.medigoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmFu4XzjJ35gXaaVsGtUPiIuZdxBNd_QI',
    appId: '1:919617836894:ios:67030648c4ccdc0a83a1cf',
    messagingSenderId: '919617836894',
    projectId: 'medigo-app-73a5d',
    storageBucket: 'medigo-app-73a5d.firebasestorage.app',
    iosBundleId: 'com.example.medigoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGjeBaWJ3NsVlaM0SLDjWxuXhueimbgI',
    appId: '1:919617836894:web:55230f330334831383a1cf',
    messagingSenderId: '919617836894',
    projectId: 'medigo-app-73a5d',
    authDomain: 'medigo-app-73a5d.firebaseapp.com',
    storageBucket: 'medigo-app-73a5d.firebasestorage.app',
    measurementId: 'G-KE1QMH3XW6',
  );
}
